import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: 'bet/home',
    title: 'MENUITEMS.DASHBOARD.TEXT',
    iconType: 'feather',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    role:["ROLE_BET"]
  },
  // {
  //   path: 'impiegato/home',
  //   title: 'MENUITEMS.DASHBOARD.TEXT',
  //   iconType: 'feather',
  //   icon: 'home',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [],
  //   role:["ROLE_USER"]
  // },
  //
  // {
  //   path: 'admin/gestioneImpiegato',
  //   title: 'MENUITEMS.ADMIN.GESTIONE',
  //   iconType: 'feather',
  //   icon: 'calendar',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [],
  //   role:["ROLE_ADMIN"]
  // },
  //
  // {
  //   path: 'admin/gestionetimesheet',
  //   title: 'MENUITEMS.ADMIN.GESTIONET',
  //   iconType: 'feather',
  //   icon: 'calendar',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [],
  //   role:["ROLE_ADMIN"]
  // },

  // {
  //   path: '',
  //   title: 'DASHBOARD',
  //   iconType: 'feather',
  //   icon: 'calendar',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [
  //     {
  //       path: 'impiegato/timesheet',
  //       title: 'BET1',
  //       iconType: 'feather',
  //       icon: 'calendar',
  //       class: '',
  //       groupTitle: false,
  //       badge: 'New',
  //       badgeClass: 'badge bg-blue sidebar-badge float-end',
  //       submenu: [],
  //       role:["ROLE_BET"]
  //     },
  //     {
  //       path: 'impiegato/riepilogoTimesheet',
  //       title: 'BET2',
  //       iconType: 'feather',
  //       icon: 'calendar',
  //       class: '',
  //       groupTitle: false,
  //       badge: 'New',
  //       badgeClass: 'badge bg-blue sidebar-badge float-end',
  //       submenu: [],
  //       role:["ROLE_BET"]
  //     },
  //   ],
  //   role:["ROLE_BET"]
  // },

  // {
  //   path: '',
  //   title: 'MENUITEMS.EMAIL.TEXT',
  //   iconType: 'feather',
  //   icon: 'mail',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role:["ROLE_USER","ROLE_ADMIN"],
  //   submenu: [
  //     {
  //       path: '/email/inbox',
  //       title: 'MENUITEMS.EMAIL.LIST.INBOX',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //       role:["ROLE_USER","ROLE_ADMIN"],
  //     },
  //     {
  //       path: '/email/compose',
  //       title: 'MENUITEMS.EMAIL.LIST.COMPOSE',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role:["ROLE_USER","ROLE_ADMIN"],
  //       submenu: [],
  //     },
  //     {
  //       path: '/email/read-mail',
  //       title: 'MENUITEMS.EMAIL.LIST.READ',
  //       iconType: '',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role:["ROLE_ADMIN"],
  //       submenu: [],
  //     },
  //   ],
  // },
];
